plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.stackr'
version = '0.1.0'

android {
  namespace "com.stackr.cardvision"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
}

dependencies {
  def cameraxVersion = "1.5.0-alpha03"
  compileOnly "androidx.camera:camera-core:${cameraxVersion}"

  if (rootProject.findProject(":react-native-vision-camera") != null) {
    compileOnly project(":react-native-vision-camera")
  }
}
