import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {assertEnvironment,assertSource,assertBucket,BUCKET,STAGING,selectScope,nameKey,bindRows,assetRow,assertReviewAsset,PREFIX} from './stage.mjs';
const rows=JSON.parse(readFileSync(process.env.QUEUE1_RECEIPTS||'queue1-source/receipts.json','utf8'));
const r=rows[0],p={id:'printing',set_id:'set',collector_number:r.collector_number,english_display_name:r.card_name,language_code:'en',game_code:'pokemon',deprecated_at:null};
const v={id:'variant',printing_id:p.id,language_code:'en',game_code:'pokemon',variant_code:r.variant_code,finish_code:r.finish_code,deprecated_at:null};
const set={id:'set',set_code:r.set_code,game_code:'pokemon',language_code:'en'};
const source={id:'source',code:'pokemon_tcg_api',active:true,licence_status:'under_review'};
test('fixed cohort contains all 348 unique images',()=>assert.equal(selectScope(rows).length,348));
test('production environment refused',()=>assert.throws(()=>assertEnvironment('https://oakdbbzdqwurpjnoqhmu.supabase.co',true)));
test('explicit execute required',()=>assert.throws(()=>assertEnvironment(`https://${STAGING}.supabase.co`,false)));
test('staging target allowed',()=>assert.doesNotThrow(()=>assertEnvironment(`https://${STAGING}.supabase.co`,true)));
test('source must not be denied',()=>assert.throws(()=>assertSource({...source,licence_status:'denied'})));
test('inactive source refused',()=>assert.throws(()=>assertSource({...source,active:false})));
test('review source retained not promoted',()=>assert.doesNotThrow(()=>assertSource(source)));
test('public bucket refused',()=>assert.throws(()=>assertBucket({id:BUCKET,public:true})));
test('different private bucket refused',()=>assert.throws(()=>assertBucket({id:'card-scans',public:false})));
test('exact private bucket accepted',()=>assert.doesNotThrow(()=>assertBucket({id:BUCKET,public:false})));
test('foreign language refused',()=>assert.throws(()=>selectScope([{...r,language_code:'ja'},...rows.slice(1)])));
test('path traversal refused',()=>assert.throws(()=>selectScope([{...r,image_file:'../../other'},...rows.slice(1)])));
test('duplicate identity refused',()=>assert.throws(()=>selectScope([r,r,...rows.slice(2)])));
test('collector leading zeros preserved',()=>{const x=structuredClone(rows);x.find(q=>q.collector_number==='SV001').collector_number='SV1';assert.throws(()=>selectScope(x));});
test('limited typography match',()=>assert.equal(nameKey('Entei-GX'),nameKey('Entei GX')));
test('actual staging binding resolved',()=>assert.equal(bindRows([r],set,[p],[v])[0].staging_printing_id,p.id));
test('ambiguous printing refused',()=>assert.throws(()=>bindRows([r],set,[p,{...p,id:'other'}],[v])));
test('wrong card name refused',()=>assert.throws(()=>bindRows([r],set,[{...p,english_display_name:'Pikachu'}],[v])));
test('wrong finish refused',()=>assert.throws(()=>bindRows([r],set,[p],[{...v,finish_code:'different'}])));
test('private asset retains source and is printing-level only',()=>{
 const bound=bindRows([r],set,[p],[v])[0];const a=assetRow(bound,source,{key:'private/key'},[],new Date().toISOString());
 assertReviewAsset(a,bound);assert.equal(a.variant_id,null);assert.equal(a.permission_status,'under_review');assert.equal(a.rights_status,'under_review');assert.equal(a.publicly_servable,false);assert.equal(a.recognition_reference_eligible,false);assert.equal(a.source_id,source.id);
 assert.ok(a.asset_id.startsWith(PREFIX));assert.throws(()=>assertReviewAsset({...a,publicly_servable:true},bound));
});
