import fs from 'node:fs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const metadata=read('tools/newsets480-publish-20260927/cohort.json');
const references=read('tools/newsets480-publish-20260927/references.json').records;
const stored=read('tools/anniversary201-publish-20260927/cohort.json');
const hashes=new Map(references.map(r=>[r.bindings.production.printing_id,r.sha256]));
for(const r of stored)hashes.set(r.printing_id,r.image_sha256);
const report={observed_at:new Date().toISOString(),base:'https://api.stackrtcg.com',scope:'All 480 frozen Storm/anniversary identities via paginated public set cards; 12 card-detail and exact set/number search cases. Full response body decoded before timing ends. First and repeat requests do not establish cold shared caches or device latency.',requests:[],sets:[],details:[],searches:[]};
async function get(path,phase){const start=performance.now();try{const r=await fetch(report.base+path,{signal:AbortSignal.timeout(20000)}),body=await r.json();const evidence={path,phase,status:r.status,ms:Math.round(performance.now()-start),ok:r.ok&&!body.error};report.requests.push(evidence);if(!evidence.ok)throw new Error('HTTP/API failure '+r.status);return body;}catch(e){if(!report.requests.some(r=>r.path===path&&r.phase===phase))report.requests.push({path,phase,ok:false,ms:Math.round(performance.now()-start),error:e.message});throw e;}}
function check(c,e,s){const id=e.bindings.production.printing_id;return {printing_id:id,identity:!!c&&c.cardId===id&&c.languageCode===e.language_code&&c.set?.setId===s.ids.production&&c.collectorNumber?.value===e.collector_number&&c.names?.native?.normalize('NFC')===e.native_name.normalize('NFC'),artwork:!!c?.variants?.length&&c.variants.every(v=>v.image?.cardId===id&&v.image?.contentSha256===hashes.get(id)),details:!!c&&c.details?.artist===(e.artist??null)&&c.details?.supertype===(e.supertype??null)&&JSON.stringify(c.details?.subtypes??[])===JSON.stringify(e.subtypes??[])};}
for(const s of metadata.sets){const expected=metadata.cards.filter(c=>c.language_code===s.language_code&&c.provider_set_code===s.provider_set_code),cards=[],seen=new Set();let cursor=null;const result={set_code:s.set_code,language:s.language_code,expected:expected.length};try{do{const path='/v1/sets/'+s.ids.production+'/cards?limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):'');const b=await get(path,'first');cards.push(...(b.data?.cards??[]));cursor=b.meta?.pagination?.nextCursor;if(cursor&&seen.has(cursor))throw new Error('Repeated cursor');if(cursor)seen.add(cursor);if(seen.size>10)throw new Error('Unexpected pagination bound');}while(cursor);const byId=new Map(cards.map(c=>[c.cardId,c]));result.returned=cards.length;result.unique=byId.size;result.checks=expected.map(e=>check(byId.get(e.bindings.production.printing_id),e,s));result.identity_passed=result.checks.filter(c=>c.identity).length;result.artwork_passed=result.checks.filter(c=>c.artwork).length;result.details_passed=result.checks.filter(c=>c.details).length;await get('/v1/sets/'+s.ids.production+'/cards?limit=100','repeat');for(const e of [expected[0],expected[Math.floor(expected.length/2)],expected.at(-1)]){const id=e.bindings.production.printing_id;for(const phase of ['first','repeat']){const d=await get('/v1/cards/'+id,phase);report.details.push({...check(d.data?.card,e,s),phase});}const path='/v1/search?'+new URLSearchParams({q:e.collector_number,setId:s.ids.production,language:s.language_code,limit:'5'});for(const phase of ['first','repeat']){const b=await get(path,phase);const results=b.data?.results??[];report.searches.push({printing_id:id,phase,top_one:results[0]?.card?.cardId===id,top_five:results.some(r=>r.card?.cardId===id)});}}}catch(e){result.error=e.message;}report.sets.push(result);console.log(JSON.stringify({set:result.set_code,language:result.language,identity:result.identity_passed,artwork:result.artwork_passed,details:result.details_passed,error:result.error}));}
report.finished_at=new Date().toISOString();report.identity_passed=report.sets.reduce((n,s)=>n+(s.identity_passed??0),0);report.artwork_passed=report.sets.reduce((n,s)=>n+(s.artwork_passed??0),0);report.details_passed=report.sets.reduce((n,s)=>n+(s.details_passed??0),0);report.expected=480;
fs.writeFileSync(process.argv[2]??'docs/releases/october-1-public-api-acceptance-20260929.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({identity:report.identity_passed,artwork:report.artwork_passed,details:report.details_passed,expected:480,requests:report.requests.length}));
process.exitCode=report.identity_passed===480&&report.artwork_passed===480&&report.details_passed===480&&report.searches.every(r=>r.top_one)?0:1;
