import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import test from 'node:test'; import assert from 'node:assert/strict';
import {ARCHIVES,FOUR_ARCHIVE_COLLECTORS,validatePlan,validateRow,correctionPlan,frozenConstants,exceptionLedger,validateApproval,sourcesFor,assertConfig} from './publish.mjs';
import {TCGPLAYER_SOURCE} from '../native96-publish-20260930/publish.mjs';
const read=n=>JSON.parse(readFileSync(new URL(n,import.meta.url))); const bytes=readFileSync(new URL('./cohort.json.gz',import.meta.url)); const receipt=read('./plan-receipt.json'),rows=JSON.parse(gunzipSync(bytes)),plan=correctionPlan(),constants=frozenConstants(),ledger=exceptionLedger(); const validate=r=>validateRow(r,ledger.get(r.printing_id),constants,plan);
test('frozen E5 scope is exactly 84 fronts, 81 repairs, three unchanged names and 336 objects',()=>{assert.equal(validatePlan(bytes,receipt).length,84);assert.equal(plan.length,81);assert.equal(rows.filter(r=>r.metadata_correction_required).length,81);assert.deepEqual(rows.filter(r=>!r.metadata_correction_required).map(r=>`${r.set_code}/${r.collector_number}`).sort(),['E5/077','E5/085','E5/086']);assert.equal(rows.flatMap(r=>r.objects).length,336);for(const d of [{fronts:83},{native_name_corrections:80},{derivative_references:251},{object_references:335},{unchanged_native_names:2}])assert.throws(()=>validatePlan(bytes,{...receipt,...d}));});
test('two archives bind exactly the four E5 energy/final collectors and reject swaps',()=>{assert.equal(ARCHIVES.length,2);assert.deepEqual(FOUR_ARCHIVE_COLLECTORS,['087','088','089','091']);const four=rows.filter(r=>FOUR_ARCHIVE_COLLECTORS.includes(r.collector_number));const eighty=rows.filter(r=>!FOUR_ARCHIVE_COLLECTORS.includes(r.collector_number));assert.equal(four.length,4);assert.equal(eighty.length,80);for(const sample of [...four,...eighty]){validate(sample);const changed=structuredClone(sample);changed.objects[0].artifact_id=sample.objects[0].artifact_id===ARCHIVES[0].id?ARCHIVES[1].id:ARCHIVES[0].id;assert.throws(()=>validate(changed));}const swapped=structuredClone(four[0]);swapped.collector_number=eighty[0].collector_number;assert.throws(()=>validate(swapped));});
test('E5 review, source group, denominator and repair bindings reject drift',()=>{const sample=rows.find(r=>r.metadata_correction_required);validate(sample);for(const m of [r=>r.evidence.provider_group_id=23733,r=>r.evidence.independent_visual_review.observed_printed_number=`${r.collector_number}/087`,r=>r.set_id='00000000-0000-4000-8000-000000000000',r=>r.evidence.independent_visual_review.source_url='https://example.com',r=>r.card_native_name='wrong']){const x=structuredClone(sample);m(x);assert.throws(()=>validate(x));}});
test('repair-plan, source provenance, object identity and approval scope reject tampering',()=>{const sample=rows.find(r=>r.metadata_correction_required),index=plan.findIndex(p=>p.printing_id===sample.printing_id);validate(sample);
 for(const delta of [{proposed_native_name:'wrong'},{source_url:'https://example.com'},{original_sha256:'f'.repeat(64)},{observed_printed_number:'001/999'},{reviewer:'other'}]){const changed=structuredClone(plan);Object.assign(changed[index],delta);assert.throws(()=>validateRow(sample,ledger.get(sample.printing_id),constants,changed));}
 for(const mutate of [r=>r.source_code='other',r=>r.evidence.provider_id='bad',r=>r.objects[1].file='../bad.webp',r=>r.objects[0].mime_type='image/png',r=>r.objects[2].role='original',r=>r.objects[3].artifact_id=1,r=>r.objects[0].width=0]){const changed=structuredClone(sample);mutate(changed);assert.throws(()=>validate(changed));}
 const approval=read('./approval.json');for(const delta of [{approved:false},{store_resize_display:false},{source_wide_approval:true},{native_name_corrections:80},{source_counts:{tcgplayer_card_artwork:83}}])assert.throws(()=>validateApproval({...approval,...delta}));
});
test('three reviewed E5 names stay unchanged',()=>{for(const sample of rows.filter(r=>!r.metadata_correction_required)){validate(sample);for(const m of [r=>r.metadata_correction_required=true,r=>r.card_native_name='wrong',r=>r.evidence.independent_visual_review.metadata_correction_required=true]){const x=structuredClone(sample);m(x);assert.throws(()=>validate(x));}}});
test('approval, config and source resolver remain constrained',async()=>{const a=read('./approval.json');validateApproval(a);for(const d of [{fronts:83},{native_name_corrections:80},{source_wide_approval:true}])assert.throws(()=>validateApproval({...a,...d}));assert.throws(()=>assertConfig({}));const calls=[];const db={query:async(sql,args)=>{calls.push(sql);return {rows:sql.startsWith('select')?[{...TCGPLAYER_SOURCE,id:'ja'}]:[]};}};assert.equal((await sourcesFor(db,receipt,'production')).size,1);assert.equal((await sourcesFor(db,receipt,'staging')).size,1);assert.equal(calls.filter(x=>x.startsWith('insert')).length,1);});
