import type { ImageSourcePropType } from 'react-native';

import type { MagazineSetCoverSourceResolver } from './magazineSetCovers';

// Keep static Metro requires outside the matcher. Tests pass a source resolver
// and therefore do not load image files.
const SOURCES: Record<string, () => ImageSourcePropType> = {
  'corocoro-comic-1996-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-04-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-05-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-06-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-07-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-08-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-09-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-10-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-11': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-11-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1996-12': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1996-12-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-01': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-01-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-02': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-02-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-03': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-03-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-04-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-05-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-06-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-07-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-08-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-09-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-10-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-11': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-11-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1997-12': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1997-12-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-01': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-01-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-02': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-02-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-03': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-03-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-04-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-05-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-06-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-07-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-08-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-09-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-10-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-11': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-11-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1998-12': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1998-12-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-01': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-01-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-02': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-02-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-03': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-03-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-04-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-05-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-06-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-07-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-08-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-09-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-10-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-11': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-11-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-1999-12': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/1999-12-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-01': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-01-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-02': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-02-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-03': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-03-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-04-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-05-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-06-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-07-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-08-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-09-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-10-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-11': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-11-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2000-12': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2000-12-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-01': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-01-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-02': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-02-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-03': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-03-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-04-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-05-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-06-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-07-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-08-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-09-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-10-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-11': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-11-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-comic-2001-12': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Comic/2001-12-CoroCoro-Comic.png') as ImageSourcePropType,
  'corocoro-ichiban-2021-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/CoroCoro Ichiban/2021-06-CoroCoro-Ichiban.png') as ImageSourcePropType,
  'pokemon-fan-japan-2021-issue-73': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan Japan/2021-Issue-73-Pokemon-Fan-Japan.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-01': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-01.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-02': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-02.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-03': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-03.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-04': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-04.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-05': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-05.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-06': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-06.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-07': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-07.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-08': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-08.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-09': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-09.png') as ImageSourcePropType,
  'pokemon-fan-us-issue-10': () => require('../assets/Pokemon_Magazine_Cover_Art_PNGs/Pokemon Fan US/Pokemon-Fan-US-Issue-10.png') as ImageSourcePropType,
};

export const MAGAZINE_SET_COVER_ASSET_KEYS = Object.freeze(Object.keys(SOURCES));

export const getMagazineSetCoverAssetSource: MagazineSetCoverSourceResolver = (key) => SOURCES[key]?.() ?? null;
