export const stackrIcons = {
  binders: require('../assets/rev2/02-navigation-icons/binders.png'),
  chase: require('../assets/rev2/02-navigation-icons/chase.png'),
  duplicates: require('../assets/rev2/02-navigation-icons/duplicates.png'),
  favorite: require('../assets/rev2/02-navigation-icons/favorite.png'),
  hub: require('../assets/rev2/02-navigation-icons/hub.png'),
  inbound: require('../assets/rev2/02-navigation-icons/inbound.png'),
  info: require('../assets/rev2/02-navigation-icons/info.png'),
  marketMovers: require('../assets/rev2/02-navigation-icons/market-movers.png'),
  marketplace: require('../assets/rev2/02-navigation-icons/marketplace.png'),
  notifications: require('../assets/rev2/02-navigation-icons/notifications.png'),
  outbound: require('../assets/rev2/02-navigation-icons/outbound.png'),
  pokedex: require('../assets/rev2/02-navigation-icons/pokedex.png'),
  priceBuilder: require('../assets/rev2/02-navigation-icons/price-builder.png'),
  profile: require('../assets/rev2/02-navigation-icons/profile.png'),
  protect: require('../assets/rev2/02-navigation-icons/protect.png'),
  scanCard: require('../assets/rev2/02-navigation-icons/scan-card-clean.png'),
  searchCard: require('../assets/rev2/02-navigation-icons/search-card-clean.png'),
  sellCard: require('../assets/rev2/02-navigation-icons/sell-card.png'),
  setDiscovery: require('../assets/rev2/02-navigation-icons/Set Discovery.png'),
  sellerMode: require('../assets/rev2/02-navigation-icons/seller-mode.png'),
  social: require('../assets/rev2/02-navigation-icons/social.png'),
  stock: require('../assets/rev2/02-navigation-icons/price-builder.png'),
  trade: require('../assets/rev2/02-navigation-icons/trade.png'),
  protectionBronze: require('../assets/rev2/10-market-trade/protection-tiers/Bronze.png'),
  protectionSilver: require('../assets/rev2/10-market-trade/protection-tiers/silver.png'),
  protectionGold: require('../assets/rev2/10-market-trade/protection-tiers/gold.png'),
};

export type StackrIconKey = keyof typeof stackrIcons;
