/** Strict HEAD-only verification of the local CJK provider candidate queue. */
import { createHash } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { isAbsolute, relative, resolve } from 'node:path';
/**
 * Deliberately local to this audit lane.  The generic TCGdex probe imports a
 * separate potential-artwork candidate pipeline that is not required here.
 */
export const MAX_TCGDEX_AVAILABILITY_PROBE_CONCURRENCY = 8;
export const MAX_TCGDEX_AVAILABILITY_PROBE_TIMEOUT_MS = 30_000;
export type ProbeTransport = (request: {
  url: string;
  method: 'HEAD';
  redirect: 'manual';
  signal: AbortSignal;
}) => Promise<{ status: number; headers: { get: (name: string) => string | null }; url?: string }>;

export async function defaultHeadTransport(request: Parameters<ProbeTransport>[0]) {
  const response = await fetch(request.url, {
    method: request.method,
    redirect: request.redirect,
    signal: request.signal,
  });
  return { status: response.status, headers: response.headers, url: response.url || request.url };
}

type Row = Record<string, unknown>;
type Candidate = { canonical_variant_id: string; language: string; provider_image_url: string; disposition: string };
export type HeadProbeRow = { canonical_variant_id: string; language: string; requested_url: string; final_url: string; request_method: 'HEAD'; status_code: number | null; mime_type: string | null; content_length: number | null; redirect_chain: { status_code: number; from_url: string; to_url: string }[]; outcome: 'available' | 'unavailable' | 'error'; error_code: string | null; observed_at: string; image_body_downloaded: false };
const SHA256 = /^[a-f0-9]{64}$/; const ASSET_HOST = 'assets.tcgdex.net'; const REDIRECTS = new Set([301, 302, 303, 307, 308]); const MAX_REDIRECTS = 3;
function hash(value: string | Buffer) { return createHash('sha256').update(value).digest('hex'); }
function row(value: unknown): value is Row { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value: unknown) { return typeof value === 'string' && value.trim() ? value.trim() : null; }
function stable(value: unknown): unknown { if (Array.isArray(value)) return value.map(stable); if (row(value)) return Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])); return value; }
function json(value: unknown) { return `${JSON.stringify(stable(value), null, 2)}\n`; }
function file(path: string, label: string) { if (!existsSync(path) || lstatSync(path).isSymbolicLink() || !lstatSync(path).isFile()) throw new Error(`${label} must be a regular file.`); return readFileSync(path, 'utf8'); }
function assetLowUrl(value: string) {
  let parsed: URL; try { parsed = new URL(value); } catch { throw new Error('Candidate provider image URL is invalid.'); }
  if (parsed.protocol !== 'https:' || parsed.hostname.toLowerCase() !== ASSET_HOST || parsed.port || parsed.username || parsed.password || parsed.search || parsed.hash || !/^\/(ja|zh-tw|zh-cn)\/[A-Za-z0-9._~-]+(?:\/[A-Za-z0-9._~-]+){2,}$/.test(parsed.pathname)) throw new Error('Candidate provider image URL is outside the exact TCGdex asset allowlist.');
  parsed.hostname = ASSET_HOST;
  return `${parsed.toString().replace(/\/$/, '')}/low.webp`;
}
function exactLowUrl(value: string) { const expected = assetLowUrl(value.replace(/\/low\.webp$/, '')); if (value !== expected) throw new Error('HEAD target is not the exact reviewed provider base plus /low.webp.'); return expected; }
function headers(response: Awaited<ReturnType<ProbeTransport>>) { const raw = response.headers.get('content-type'); const mime = raw ? raw.split(';')[0].trim().toLowerCase() : null; const length = response.headers.get('content-length'); return { mime, length: length && /^\d+$/.test(length) && Number.isSafeInteger(Number(length)) ? Number(length) : null, invalidLength: Boolean(length && (!/^\d+$/.test(length) || !Number.isSafeInteger(Number(length)))) }; }
async function head(transport: ProbeTransport, url: string, timeoutMs: number) { const controller = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; try { return await Promise.race([transport({ url, method: 'HEAD', redirect: 'manual', signal: controller.signal }), new Promise<never>((_, reject) => { timer = setTimeout(() => { controller.abort(); reject(new Error('timeout')); }, timeoutMs); })]); } finally { if (timer) clearTimeout(timer); } }
async function probe(candidate: Candidate, transport: ProbeTransport, timeoutMs: number): Promise<HeadProbeRow> {
  const requested = assetLowUrl(candidate.provider_image_url); let current = requested; const redirects: HeadProbeRow['redirect_chain'] = []; const observed = new Date().toISOString();
  for (;;) {
    let response: Awaited<ReturnType<ProbeTransport>>; try { response = await head(transport, current, timeoutMs); } catch (error) { return { canonical_variant_id: candidate.canonical_variant_id, language: candidate.language, requested_url: requested, final_url: current, request_method: 'HEAD', status_code: null, mime_type: null, content_length: null, redirect_chain: redirects, outcome: 'error', error_code: error instanceof Error && error.message === 'timeout' ? 'timeout' : 'transport_error', observed_at: observed, image_body_downloaded: false }; }
    if (response.url && response.url !== current) return { canonical_variant_id: candidate.canonical_variant_id, language: candidate.language, requested_url: requested, final_url: current, request_method: 'HEAD', status_code: response.status, mime_type: null, content_length: null, redirect_chain: redirects, outcome: 'error', error_code: 'transport_redirect_not_manual', observed_at: observed, image_body_downloaded: false };
    const meta = headers(response); if (meta.invalidLength) return { canonical_variant_id: candidate.canonical_variant_id, language: candidate.language, requested_url: requested, final_url: current, request_method: 'HEAD', status_code: response.status, mime_type: meta.mime, content_length: null, redirect_chain: redirects, outcome: 'error', error_code: 'invalid_content_length', observed_at: observed, image_body_downloaded: false };
    if (REDIRECTS.has(response.status)) { const location = response.headers.get('location'); let target: string; try { target = exactLowUrl(new URL(location ?? '', current).toString()); } catch { return { canonical_variant_id: candidate.canonical_variant_id, language: candidate.language, requested_url: requested, final_url: current, request_method: 'HEAD', status_code: response.status, mime_type: meta.mime, content_length: meta.length, redirect_chain: redirects, outcome: 'error', error_code: 'redirect_target_not_exact_allowlisted_path', observed_at: observed, image_body_downloaded: false }; } if (target !== requested || redirects.length >= MAX_REDIRECTS) return { canonical_variant_id: candidate.canonical_variant_id, language: candidate.language, requested_url: requested, final_url: current, request_method: 'HEAD', status_code: response.status, mime_type: meta.mime, content_length: meta.length, redirect_chain: redirects, outcome: 'error', error_code: target !== requested ? 'redirect_target_path_changed' : 'redirect_limit_exceeded', observed_at: observed, image_body_downloaded: false }; redirects.push({ status_code: response.status, from_url: current, to_url: target }); current = target; continue; }
    const outcome: HeadProbeRow['outcome'] = response.status === 200 && meta.mime?.startsWith('image/') ? 'available' : response.status === 404 || response.status === 410 ? 'unavailable' : 'error';
    return { canonical_variant_id: candidate.canonical_variant_id, language: candidate.language, requested_url: requested, final_url: current, request_method: 'HEAD', status_code: response.status, mime_type: meta.mime, content_length: meta.length, redirect_chain: redirects, outcome, error_code: outcome === 'error' ? (response.status === 200 ? 'mime_not_image' : 'http_status_not_promotable') : null, observed_at: observed, image_body_downloaded: false };
  }
}
export async function runCurrentCjkProviderImageHeadProbe(input: { probe: boolean; queueBody: string; queueSha256: string; transport?: ProbeTransport; concurrency?: number; timeoutMs?: number }) {
  if (input.probe !== true) throw new Error('Use the exact --probe flag to authorize HEAD requests.'); if (!SHA256.test(input.queueSha256) || hash(input.queueBody) !== input.queueSha256) throw new Error('Candidate queue hash verification failed.');
  const concurrency = input.concurrency ?? 4; const timeoutMs = input.timeoutMs ?? 5_000; if (!Number.isSafeInteger(concurrency) || concurrency < 1 || concurrency > MAX_TCGDEX_AVAILABILITY_PROBE_CONCURRENCY) throw new Error(`Concurrency must be 1-${MAX_TCGDEX_AVAILABILITY_PROBE_CONCURRENCY}.`); if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 1 || timeoutMs > MAX_TCGDEX_AVAILABILITY_PROBE_TIMEOUT_MS) throw new Error(`Timeout must be 1-${MAX_TCGDEX_AVAILABILITY_PROBE_TIMEOUT_MS}ms.`);
  const candidates = input.queueBody.split(/\r?\n/).filter(Boolean).flatMap((line): Candidate[] => { const value = JSON.parse(line) as unknown; if (!row(value) || !text(value.canonical_variant_id) || !text(value.language) || !text(value.disposition)) throw new Error('Candidate queue row violates the reviewed candidate contract.'); if (value.disposition !== 'candidate_url_declared_in_pinned_provider_snapshot') return []; if (!text(value.provider_image_url)) throw new Error('Provider-declared candidate lacks its exact image base URL.'); return [{ canonical_variant_id: value.canonical_variant_id as string, language: value.language as string, provider_image_url: value.provider_image_url as string, disposition: value.disposition as string }]; });
  if (!candidates.length || new Set(candidates.map((candidate) => candidate.canonical_variant_id)).size !== candidates.length) throw new Error('Candidate queue must contain unique non-empty candidates.');
  const transport = input.transport ?? defaultHeadTransport; const results: HeadProbeRow[] = new Array(candidates.length); let cursor = 0; await Promise.all(Array.from({ length: Math.min(concurrency, candidates.length) }, async () => { for (;;) { const index = cursor++; if (index >= candidates.length) return; results[index] = await probe(candidates[index], transport, timeoutMs); } }));
  return { rows: results, summary: { requested: results.length, available: results.filter((value) => value.outcome === 'available').length, unavailable: results.filter((value) => value.outcome === 'unavailable').length, error: results.filter((value) => value.outcome === 'error').length, provider_network_requests_performed: true, image_bodies_downloaded: false, database_modified: false, storage_modified: false, catalogue_modified: false, queue_sha256: input.queueSha256, policy: { request_method: 'HEAD', allowlisted_host: ASSET_HOST, append_only: '/low.webp', max_concurrency: MAX_TCGDEX_AVAILABILITY_PROBE_CONCURRENCY, timeout_ms: timeoutMs, redirects_manual: true, redirects_must_remain_exact_path: true } } };
}
function args(argv: string[]) { return new Map(argv.filter((value) => value.startsWith('--') && value.includes('=')).map((value) => { const [key, ...rest] = value.slice(2).split('='); return [key, rest.join('=')]; })); }
function outputDir(value: string) { const root = resolve('.tmp/cjk-provider-image-live-head-probes'); const target = resolve(value); const rel = relative(root, target); if (!rel || rel.startsWith('..') || isAbsolute(rel) || existsSync(target)) throw new Error('Output must be a new child directory under .tmp/cjk-provider-image-live-head-probes.'); return { root, target }; }
async function main() { const argv = process.argv.slice(2); const values = args(argv); if (argv.some((value) => value.startsWith('--probe='))) throw new Error('Use the exact --probe flag.'); const probeAuthorized = argv.includes('--probe'); const source = resolve(values.get('source') ?? '.tmp/cjk-provider-image-coverage-audit/current-gap-audit-20260904-v1'); const manifest = JSON.parse(file(resolve(source, 'manifest.json'), 'candidate manifest')) as Row; const expected = text((row(manifest.output_sha256) ? manifest.output_sha256 : null)?.['cjk-provider-image-candidates.jsonl'])?.toLowerCase(); const queuePath = resolve(source, 'cjk-provider-image-candidates.jsonl'); const queueBody = file(queuePath, 'candidate queue'); if (!expected || !SHA256.test(expected) || hash(queueBody) !== expected) throw new Error('Candidate queue is not hash-bound to its manifest.'); if (!probeAuthorized) { process.stdout.write(`${JSON.stringify({ ok: true, mode: 'validation', provider_network_requests_performed: false, queue_sha256: expected })}\n`); return; } if (!values.has('output')) throw new Error('--probe requires --output=<new-report-dir>.'); const output = outputDir(values.get('output')!); const result = await runCurrentCjkProviderImageHeadProbe({ probe: true, queueBody, queueSha256: expected, concurrency: values.has('concurrency') ? Number(values.get('concurrency')) : undefined, timeoutMs: values.has('timeout-ms') ? Number(values.get('timeout-ms')) : undefined }); const rows = `${result.rows.map((value) => JSON.stringify(value)).join('\n')}\n`; const report = json(result.summary); mkdirSync(output.root, { recursive: true }); mkdirSync(output.target); writeFileSync(resolve(output.target, 'cjk-provider-image-head-results.jsonl'), rows, { flag: 'wx' }); writeFileSync(resolve(output.target, 'cjk-provider-image-head-report.json'), report, { flag: 'wx' }); writeFileSync(resolve(output.target, 'manifest.json'), json({ schema_version: '1.0.0', queue_sha256: expected, local_catalogue_mutation: false, storage_mutation: false, image_bodies_downloaded: false, output_sha256: { 'cjk-provider-image-head-results.jsonl': hash(rows), 'cjk-provider-image-head-report.json': hash(report) } }), { flag: 'wx' }); process.stdout.write(`${JSON.stringify({ ok: true, ...result.summary, output: output.target })}\n`); }
if (require.main === module) main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; });
