create table if not exists public.seller_inventory_items (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  card_id text not null references public.pokemon_cards(id) on delete cascade,
  set_id text null,
  condition text not null,
  quantity integer not null default 0 check (quantity >= 0),
  asking_price numeric null,
  buy_price numeric null,
  notes text null,
  card_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_sale_transactions (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sold_price numeric null,
  estimated_value numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.seller_sale_transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id text not null references public.seller_sale_transactions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  inventory_item_id text null,
  card_id text not null references public.pokemon_cards(id) on delete cascade,
  card_name text not null,
  set_name text null,
  condition text not null,
  quantity integer not null default 1 check (quantity > 0),
  estimated_unit_price numeric null,
  image_small text null,
  created_at timestamptz not null default now()
);

create index if not exists seller_inventory_items_user_idx
  on public.seller_inventory_items(user_id);

create index if not exists seller_inventory_items_user_card_idx
  on public.seller_inventory_items(user_id, card_id);

create index if not exists seller_sale_transactions_user_created_idx
  on public.seller_sale_transactions(user_id, created_at desc);

create index if not exists seller_sale_transaction_items_user_idx
  on public.seller_sale_transaction_items(user_id);

alter table public.seller_inventory_items enable row level security;
alter table public.seller_sale_transactions enable row level security;
alter table public.seller_sale_transaction_items enable row level security;

drop policy if exists "Seller inventory is private" on public.seller_inventory_items;
create policy "Seller inventory is private"
  on public.seller_inventory_items
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Seller sale transactions are private" on public.seller_sale_transactions;
create policy "Seller sale transactions are private"
  on public.seller_sale_transactions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Seller sale transaction items are private" on public.seller_sale_transaction_items;
create policy "Seller sale transaction items are private"
  on public.seller_sale_transaction_items
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

comment on table public.seller_inventory_items is
  'Seller mode stock rows, condition-specific, owned by a user.';

comment on table public.seller_sale_transactions is
  'Seller mode completed sale reports.';

comment on table public.seller_sale_transaction_items is
  'Cards included in seller mode sale reports.';
