insert into public.achievement_coin_rewards (achievement_id, coin_reward, metadata)
values
  ('C001', 10, '{"tier":"bronze","sourceTier":"Rookie","category":"Onboarding"}'::jsonb),
  ('C002', 20, '{"tier":"bronze","sourceTier":"Rookie","category":"Onboarding"}'::jsonb),
  ('C003', 15, '{"tier":"bronze","sourceTier":"Rookie","category":"Onboarding"}'::jsonb),
  ('C005', 15, '{"tier":"bronze","sourceTier":"Rookie","category":"Onboarding"}'::jsonb),
  ('C006', 15, '{"tier":"bronze","sourceTier":"Rookie","category":"Onboarding"}'::jsonb),
  ('C007', 15, '{"tier":"bronze","sourceTier":"Rookie","category":"Onboarding"}'::jsonb),
  ('C011', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C012', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C013', 30, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C014', 40, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C015', 60, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C016', 80, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C017', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C019', 50, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C020', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Collection"}'::jsonb),
  ('C021', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C022', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C023', 30, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C024', 35, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C025', 40, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C026', 50, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C029', 50, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C030', 40, '{"tier":"bronze","sourceTier":"Rookie","category":"Binders"}'::jsonb),
  ('C031', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Scanning"}'::jsonb),
  ('C032', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Scanning"}'::jsonb),
  ('C033', 35, '{"tier":"bronze","sourceTier":"Rookie","category":"Scanning"}'::jsonb),
  ('C034', 50, '{"tier":"bronze","sourceTier":"Rookie","category":"Scanning"}'::jsonb),
  ('C040', 35, '{"tier":"bronze","sourceTier":"Rookie","category":"Scanning"}'::jsonb),
  ('C041', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Sets"}'::jsonb),
  ('C042', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Sets"}'::jsonb),
  ('C043', 40, '{"tier":"bronze","sourceTier":"Rookie","category":"Sets"}'::jsonb),
  ('C051', 25, '{"tier":"bronze","sourceTier":"Rookie","category":"Wishlist"}'::jsonb),
  ('C052', 35, '{"tier":"bronze","sourceTier":"Rookie","category":"Wishlist"}'::jsonb),
  ('C053', 50, '{"tier":"bronze","sourceTier":"Rookie","category":"Wishlist"}'::jsonb),
  ('C054', 75, '{"tier":"bronze","sourceTier":"Rookie","category":"Wishlist"}'::jsonb),
  ('C055', 50, '{"tier":"bronze","sourceTier":"Rookie","category":"Grails"}'::jsonb)
on conflict (achievement_id) do update
set
  coin_reward = excluded.coin_reward,
  metadata = excluded.metadata,
  updated_at = now();
