create table if not exists audit.release_activation_events (
  id bigint generated by default as identity primary key,
  component text not null
    check (component in ('catalogue', 'embedding_index')),
  action text not null
    check (action in ('activate', 'rollback')),
  target_id uuid not null,
  previous_id uuid,
  request_id text,
  reason text,
  actor_user_id uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists release_activation_events_component_created_idx
  on audit.release_activation_events(component, created_at desc);

alter table audit.release_activation_events enable row level security;

drop policy if exists "release activation events service role only" on audit.release_activation_events;
create policy "release activation events service role only"
  on audit.release_activation_events
  for all
  to service_role
  using (true)
  with check (true);

create or replace function catalog.activate_catalogue_version(
  p_catalogue_version_id uuid,
  p_request_id text default null,
  p_reason text default null
)
returns uuid
language plpgsql
security invoker
set search_path = catalog, audit, public
as $$
declare
  candidate catalog.catalogue_versions%rowtype;
  previous_id uuid;
begin
  select * into candidate
  from catalog.catalogue_versions
  where id = p_catalogue_version_id
  for update;

  if not found then
    raise exception 'Catalogue version not found.' using errcode = 'P0001';
  end if;

  if candidate.status not in ('draft', 'published', 'deprecated', 'rolled_back') then
    raise exception 'Catalogue version cannot be activated from status %.', candidate.status
      using errcode = 'P0001';
  end if;

  select id into previous_id
  from catalog.catalogue_versions
  where status = 'published'
    and deprecated_at is null
    and id <> p_catalogue_version_id
  order by published_at desc nulls last, updated_at desc
  limit 1
  for update;

  update catalog.catalogue_versions
  set status = 'deprecated',
      deprecated_at = now(),
      deprecated_reason = coalesce(p_reason, 'Superseded by catalogue activation.'),
      superseded_by_version_id = p_catalogue_version_id,
      updated_at = now()
  where id = previous_id;

  update catalog.catalogue_versions
  set status = 'published',
      published_at = now(),
      deprecated_at = null,
      deprecated_reason = null,
      superseded_by_version_id = null,
      updated_at = now()
  where id = p_catalogue_version_id;

  insert into audit.release_activation_events(
    component, action, target_id, previous_id, request_id, reason
  ) values (
    'catalogue', 'activate', p_catalogue_version_id, previous_id, p_request_id, p_reason
  );

  return p_catalogue_version_id;
end;
$$;

create or replace function catalog.rollback_catalogue_version(
  p_catalogue_version_id uuid,
  p_request_id text default null,
  p_reason text default null
)
returns uuid
language plpgsql
security invoker
set search_path = catalog, audit, public
as $$
declare
  candidate catalog.catalogue_versions%rowtype;
  previous_id uuid;
begin
  select * into candidate
  from catalog.catalogue_versions
  where id = p_catalogue_version_id
  for update;

  if not found then
    raise exception 'Catalogue rollback target not found.' using errcode = 'P0001';
  end if;

  if candidate.status not in ('published', 'deprecated', 'rolled_back') then
    raise exception 'Catalogue rollback target must have been published previously.'
      using errcode = 'P0001';
  end if;

  select id into previous_id
  from catalog.catalogue_versions
  where status = 'published'
    and deprecated_at is null
  order by published_at desc nulls last, updated_at desc
  limit 1
  for update;

  if previous_id = p_catalogue_version_id then
    return p_catalogue_version_id;
  end if;

  update catalog.catalogue_versions
  set status = 'rolled_back',
      deprecated_at = now(),
      deprecated_reason = coalesce(p_reason, 'Rolled back by release control.'),
      superseded_by_version_id = p_catalogue_version_id,
      updated_at = now()
  where id = previous_id;

  update catalog.catalogue_versions
  set status = 'published',
      published_at = now(),
      deprecated_at = null,
      deprecated_reason = null,
      superseded_by_version_id = null,
      updated_at = now()
  where id = p_catalogue_version_id;

  insert into audit.release_activation_events(
    component, action, target_id, previous_id, request_id, reason
  ) values (
    'catalogue', 'rollback', p_catalogue_version_id, previous_id, p_request_id, p_reason
  );

  return p_catalogue_version_id;
end;
$$;

create or replace function ml.rollback_embedding_index_version(
  p_index_version_id uuid,
  p_request_id text default null,
  p_reason text default null
)
returns uuid
language plpgsql
security invoker
set search_path = ml, audit, public
as $$
declare
  candidate record;
  previous_id uuid;
  previous_model_id text;
begin
  select i.*, m.license_status, m.selection_status
    into candidate
  from ml.embedding_index_versions i
  join ml.embedding_models m on m.model_id = i.model_id
  where i.id = p_index_version_id
  for update of i, m;

  if not found then
    raise exception 'Embedding index rollback target not found.' using errcode = 'P0001';
  end if;

  if candidate.status not in ('validated', 'retired', 'active') then
    raise exception 'Embedding index rollback target is not validated.' using errcode = 'P0001';
  end if;

  if candidate.license_status <> 'production_allowed' then
    raise exception 'Embedding model is not production deployable.' using errcode = 'P0001';
  end if;

  if candidate.reference_embedding_count <= 0 or candidate.missing_embedding_count <> 0 then
    raise exception 'Embedding index rollback target is incomplete.' using errcode = 'P0001';
  end if;

  select id, model_id into previous_id, previous_model_id
  from ml.embedding_index_versions
  where status = 'active'
    and coalesce(language_code, 'all') = coalesce(candidate.language_code, 'all')
  limit 1
  for update;

  if previous_id = p_index_version_id then
    return p_index_version_id;
  end if;

  update ml.embedding_index_versions
  set status = 'retired',
      retired_at = now(),
      replaced_by = p_index_version_id,
      updated_at = now()
  where id = previous_id;

  update ml.embedding_index_versions
  set status = 'active',
      activated_at = now(),
      retired_at = null,
      replaced_by = null,
      updated_at = now()
  where id = p_index_version_id;

  update ml.embedding_models
  set selection_status = case
        when model_id = candidate.model_id then 'active'
        when model_id = previous_model_id and selection_status = 'active' then 'selected'
        else selection_status
      end,
      updated_at = now()
  where model_id in (candidate.model_id, previous_model_id);

  insert into ml.embedding_activation_events(
    request_id,
    index_version_id,
    previous_index_version_id,
    event_type,
    event_payload
  ) values (
    p_request_id,
    p_index_version_id,
    previous_id,
    'rollback',
    jsonb_build_object('reason', p_reason, 'model_id', candidate.model_id)
  );

  insert into audit.release_activation_events(
    component, action, target_id, previous_id, request_id, reason
  ) values (
    'embedding_index', 'rollback', p_index_version_id, previous_id, p_request_id, p_reason
  );

  return p_index_version_id;
end;
$$;

revoke all on audit.release_activation_events from public, anon, authenticated;
grant select, insert on audit.release_activation_events to service_role;
grant usage, select on sequence audit.release_activation_events_id_seq to service_role;

revoke all on function catalog.activate_catalogue_version(uuid, text, text) from public, anon, authenticated;
revoke all on function catalog.rollback_catalogue_version(uuid, text, text) from public, anon, authenticated;
revoke all on function ml.rollback_embedding_index_version(uuid, text, text) from public, anon, authenticated;

grant execute on function catalog.activate_catalogue_version(uuid, text, text) to service_role;
grant execute on function catalog.rollback_catalogue_version(uuid, text, text) to service_role;
grant execute on function ml.rollback_embedding_index_version(uuid, text, text) to service_role;

comment on table audit.release_activation_events is
  'Service-only audit trail for catalogue and embedding-index activation or rollback.';
