create table if not exists public.market_products (
  id text primary key,
  product_type text not null,
  name text not null,
  set_name text null,
  image_url text null,
  image_large_url text null,
  aliases text[] not null default '{}'::text[],
  search_text text not null default '',
  source text not null default 'user',
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_product_price_snapshots (
  id bigint generated by default as identity primary key,
  product_id text not null references public.market_products(id) on delete cascade,
  product_type text not null,
  product_name text not null,
  ebay_low numeric null,
  ebay_average numeric null,
  ebay_high numeric null,
  sold_count integer null,
  query text null,
  source text null,
  snapshot_at timestamptz not null default now(),
  created_by uuid null references auth.users(id) on delete set null
);

create index if not exists market_products_type_idx
  on public.market_products(product_type);

create index if not exists market_products_search_idx
  on public.market_products using gin(to_tsvector('simple', search_text));

create index if not exists market_product_price_snapshots_product_idx
  on public.market_product_price_snapshots(product_id, snapshot_at desc);

alter table public.market_products enable row level security;
alter table public.market_product_price_snapshots enable row level security;

drop policy if exists "Market products are public" on public.market_products;
create policy "Market products are public"
  on public.market_products
  for select
  using (true);

drop policy if exists "Authenticated users can add market products" on public.market_products;
create policy "Authenticated users can add market products"
  on public.market_products
  for insert
  with check (auth.uid() is not null);

drop policy if exists "Authenticated users can update market products" on public.market_products;
create policy "Authenticated users can update market products"
  on public.market_products
  for update
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

drop policy if exists "Market product prices are public" on public.market_product_price_snapshots;
create policy "Market product prices are public"
  on public.market_product_price_snapshots
  for select
  using (true);

drop policy if exists "Authenticated users can add market product prices" on public.market_product_price_snapshots;
create policy "Authenticated users can add market product prices"
  on public.market_product_price_snapshots
  for insert
  with check (auth.uid() is not null);

comment on table public.market_products is
  'Searchable product catalog for sealed products, ETBs, booster boxes, bundles, and accessories.';

comment on table public.market_product_price_snapshots is
  'Cached live product price snapshots, currently derived from eBay sold-comps.';
