const UUID = '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}';

const query = (...names) => new Set(names);

export const RATE_LIMITS = Object.freeze({
  health: { limit: 180, windowSeconds: 60 },
  catalogue: { limit: 600, windowSeconds: 60 },
  search: { limit: 60, windowSeconds: 60 },
  pricing: { limit: 120, windowSeconds: 60 },
  priceRefresh: { limit: 30, windowSeconds: 60 },
  scan: { limit: 30, windowSeconds: 60 },
  imageFallback: { limit: 5, windowSeconds: 60 },
  admin: { limit: 20, windowSeconds: 60 },
  ingestion: { limit: 5, windowSeconds: 60 },
});

const publicGet = {
  methods: ['GET'],
  auth: 'public',
  target: 'backend',
  cache: 'catalogue',
  rate: 'catalogue',
};

export const ROUTES = [
  { id: 'health', pattern: /^\/v1\/health$/, ...publicGet, target: 'gateway', cache: 'none', rate: 'health', query: query() },
  { id: 'ready', pattern: /^\/v1\/ready$/, ...publicGet, target: 'gateway', cache: 'none', rate: 'health', query: query() },
  { id: 'catalogue_manifest', pattern: /^\/v1\/catalog\/manifest$/, ...publicGet, query: query() },
  { id: 'catalogue_delta', pattern: /^\/v1\/catalog\/delta$/, ...publicGet, query: query('since', 'cursor', 'limit') },
  { id: 'languages', pattern: /^\/v1\/languages$/, ...publicGet, query: query() },
  { id: 'series', pattern: /^\/v1\/series$/, ...publicGet, query: query('language', 'game', 'cursor', 'limit') },
  { id: 'sets', pattern: /^\/v1\/sets$/, ...publicGet, query: query('language', 'game', 'seriesId', 'setCode', 'region', 'cursor', 'limit') },
  { id: 'set', pattern: new RegExp(`^/v1/sets/${UUID}$`), ...publicGet, query: query() },
  { id: 'set_cards', pattern: new RegExp(`^/v1/sets/${UUID}/cards$`), ...publicGet, query: query('language', 'cursor', 'limit') },
  { id: 'card', pattern: new RegExp(`^/v1/cards/${UUID}$`), ...publicGet, query: query() },
  { id: 'card_variants', pattern: new RegExp(`^/v1/cards/${UUID}/variants$`), ...publicGet, query: query() },
  {
    id: 'same_artwork_display_references',
    pattern: /^\/v1\/cards\/display-artwork-references$/,
    methods: ['POST'],
    auth: 'public',
    target: 'backend',
    cache: 'none',
    rate: 'catalogue',
    body: 'sameArtworkDisplayReferences',
    maxBodyBytes: 16 * 1024,
    query: query(),
  },
  {
    id: 'card_price',
    pattern: new RegExp(`^/v1/cards/${UUID}/price$`),
    ...publicGet,
    pricing: true,
    cache: 'market',
    rate: 'pricing',
    query: query('productType', 'currency', 'condition', 'grader', 'grade'),
  },
  {
    id: 'card_price_history',
    pattern: new RegExp(`^/v1/cards/${UUID}/price-history$`),
    ...publicGet,
    pricing: true,
    cache: 'market',
    rate: 'pricing',
    query: query('productType', 'currency', 'condition', 'grader', 'grade', 'observationType', 'cursor', 'limit'),
  },
  { id: 'market_movers', pattern: /^\/v1\/market\/movers$/, ...publicGet, pricing: true, cache: 'market', rate: 'pricing', query: query('productType', 'currency', 'limit') },
  { id: 'market_price_snapshots', pattern: /^\/v1\/market\/price-snapshots$/, ...publicGet, pricing: true, cache: 'none', rate: 'pricing', query: query('variantIds', 'rangeDays') },
  {
    id: 'card_price_refresh',
    pattern: new RegExp(`^/v1/cards/${UUID}/price-refresh$`),
    methods: ['POST'], auth: 'user', target: 'backend', pricing: true, cache: 'none', rate: 'priceRefresh',
    body: 'priceRefresh', maxBodyBytes: 8 * 1024, timeoutMs: 12_000,
    idempotent: true, forwardUserJwt: true, query: query(),
  },
  {
    id: 'market_price_refresh', pattern: /^\/v1\/market\/price-refresh$/,
    methods: ['POST'], auth: 'user', target: 'backend', pricing: true, cache: 'none', rate: 'priceRefresh',
    body: 'priceRefreshBatch', maxBodyBytes: 16 * 1024, timeoutMs: 12_000,
    idempotent: true, forwardUserJwt: true, query: query(),
  },
  { id: 'market_opportunities', pattern: /^\/v1\/market\/opportunities$/, ...publicGet, pricing: true, cache: 'market', rate: 'pricing', query: query('productType', 'currency', 'limit') },
  { id: 'search', pattern: /^\/v1\/search$/, ...publicGet, cache: 'search', rate: 'search', query: query('q', 'language', 'setId', 'limit') },
  {
    id: 'asset_manifest',
    pattern: /^\/v1\/assets\/manifest$/,
    ...publicGet,
    query: query('assetType', 'setId', 'printingId', 'variantId', 'cursor', 'limit'),
  },
  {
    id: 'scan_presign',
    pattern: /^\/v1\/assets\/scans\/presigned-upload$/,
    methods: ['POST'],
    auth: 'user',
    target: 'backend',
    targetPath: '/api/assets/scans/presigned-upload',
    cache: 'none',
    rate: 'imageFallback',
    body: 'scanPresign',
    maxBodyBytes: 16 * 1024,
    idempotent: true,
    forwardUserJwt: true,
    query: query(),
  },
  {
    id: 'scan_upload',
    pattern: /^\/v1\/assets\/scans\/upload$/,
    methods: ['POST'],
    auth: 'user',
    target: 'backend',
    targetPath: '/api/assets/scans/upload',
    cache: 'none',
    rate: 'imageFallback',
    body: 'image',
    maxBodyBytes: 10 * 1024 * 1024,
    idempotent: true,
    forwardUserJwt: true,
    query: query('uploadId'),
  },
  {
    id: 'recognition_identify',
    pattern: /^\/v1\/recognition\/identify$/,
    methods: ['POST'],
    auth: 'user',
    target: 'recognition',
    cache: 'none',
    rate: 'scan',
    body: 'recognitionIdentify',
    maxBodyBytes: 256 * 1024,
    idempotent: true,
    query: query(),
  },
  {
    id: 'recognition_embed',
    pattern: /^\/v1\/recognition\/embed$/,
    methods: ['POST'],
    auth: 'user',
    target: 'recognition',
    cache: 'none',
    rate: 'imageFallback',
    body: 'recognitionEmbed',
    maxBodyBytes: 128 * 1024,
    idempotent: true,
    query: query(),
  },
  {
    id: 'recognition_feedback',
    pattern: /^\/v1\/recognition\/feedback$/,
    methods: ['POST'],
    auth: 'user',
    target: 'recognition',
    cache: 'none',
    rate: 'scan',
    body: 'recognitionFeedback',
    maxBodyBytes: 64 * 1024,
    idempotent: true,
    query: query(),
  },
  {
    id: 'recognition_shadow_comparison',
    pattern: /^\/v1\/recognition\/shadow-comparisons$/,
    methods: ['POST'],
    auth: 'user',
    target: 'backend',
    targetPath: '/api/recognition-shadow-mode/items',
    cache: 'none',
    rate: 'scan',
    body: 'recognitionShadowComparison',
    maxBodyBytes: 128 * 1024,
    idempotent: true,
    forwardUserJwt: true,
    query: query(),
  },
  {
    id: 'admin_recognition_shadow_comparisons',
    pattern: /^\/v1\/admin\/recognition-shadow-comparisons$/,
    methods: ['GET'],
    auth: 'admin',
    target: 'backend',
    targetPath: '/api/recognition-shadow-mode/disagreements',
    cache: 'none',
    rate: 'admin',
    forwardUserJwt: true,
    query: query('status', 'category', 'limit'),
  },
  {
    id: 'admin_recognition_shadow_comparison_review',
    pattern: new RegExp(`^/v1/admin/recognition-shadow-comparisons/${UUID}$`),
    methods: ['PATCH'],
    auth: 'admin',
    target: 'backend',
    rewritePrefix: ['/v1/admin/recognition-shadow-comparisons', '/api/recognition-shadow-mode/disagreements'],
    cache: 'none',
    rate: 'admin',
    body: 'recognitionShadowReview',
    maxBodyBytes: 8 * 1024,
    idempotent: true,
    forwardUserJwt: true,
    query: query(),
  },
  {
    id: 'catalogue_cache_activate',
    pattern: /^\/v1\/admin\/catalogue\/cache\/activate$/,
    methods: ['POST'],
    auth: 'admin',
    target: 'gateway',
    cache: 'none',
    rate: 'admin',
    body: 'cacheActivation',
    maxBodyBytes: 8 * 1024,
    idempotent: true,
    query: query(),
  },
  {
    id: 'catalogue_ingestion_command',
    pattern: /^\/v1\/admin\/catalogue-ingestion\/(run-source|run-language|run-set|resume-import|rebuild-record)$/,
    methods: ['POST'],
    auth: 'admin',
    target: 'backend',
    rewritePrefix: ['/v1/admin/catalogue-ingestion', '/api/admin/catalogue-ingestion'],
    cache: 'none',
    rate: 'ingestion',
    body: 'catalogueAdminCommand',
    maxBodyBytes: 64 * 1024,
    idempotent: true,
    injectBackendAdminKey: true,
    query: query(),
  },
  {
    id: 'catalogue_ingestion_conflicts',
    pattern: /^\/v1\/admin\/catalogue-ingestion\/conflicts$/,
    methods: ['GET'],
    auth: 'admin',
    target: 'backend',
    rewritePrefix: ['/v1/admin/catalogue-ingestion', '/api/admin/catalogue-ingestion'],
    cache: 'none',
    rate: 'admin',
    injectBackendAdminKey: true,
    query: query('sourceId', 'conflictType', 'limit'),
  },
  {
    id: 'catalogue_ingestion_quality_report',
    pattern: /^\/v1\/admin\/catalogue-ingestion\/quality-report$/,
    methods: ['GET'],
    auth: 'admin',
    target: 'backend',
    rewritePrefix: ['/v1/admin/catalogue-ingestion', '/api/admin/catalogue-ingestion'],
    cache: 'none',
    rate: 'admin',
    injectBackendAdminKey: true,
    query: query('language', 'limit'),
  },
  {
    id: 'observability_dashboard',
    pattern: /^\/v1\/admin\/observability\/dashboard$/,
    methods: ['GET'],
    auth: 'admin',
    target: 'backend',
    targetPath: '/api/admin/observability/dashboard',
    cache: 'none',
    rate: 'admin',
    injectBackendAdminKey: true,
    query: query(),
  },
  {
    id: 'observability_evaluation',
    pattern: /^\/v1\/admin\/observability\/evaluations$/,
    methods: ['POST'],
    auth: 'admin',
    target: 'backend',
    targetPath: '/api/admin/observability/evaluations',
    cache: 'none',
    rate: 'admin',
    body: 'qualityEvaluation',
    maxBodyBytes: 512 * 1024,
    idempotent: true,
    injectBackendAdminKey: true,
    query: query(),
  },
  {
    id: 'observability_refresh',
    pattern: /^\/v1\/admin\/observability\/refresh$/,
    methods: ['POST'],
    auth: 'admin',
    target: 'backend',
    targetPath: '/api/admin/observability/refresh',
    cache: 'none',
    rate: 'admin',
    body: 'observabilityRefresh',
    maxBodyBytes: 8 * 1024,
    idempotent: true,
    injectBackendAdminKey: true,
    query: query(),
  },
  {
    id: 'asset_admin_migrate',
    pattern: /^\/v1\/admin\/assets\/migrate-existing$/,
    methods: ['POST'],
    auth: 'admin',
    target: 'backend',
    targetPath: '/api/admin/assets/migrate-existing',
    cache: 'none',
    rate: 'ingestion',
    body: 'assetMigrationCommand',
    maxBodyBytes: 64 * 1024,
    idempotent: true,
    injectBackendAdminKey: true,
    query: query(),
  },
];

export function matchRoute(pathname) {
  return ROUTES.find((route) => route.pattern.test(pathname)) ?? null;
}
